### PR TITLE
Release routing workaround.

### PR DESCRIPTION
**Pull request by gardster**

### CODE REVIEW

**Comment by mapsmetest** [comment]
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

**Comment by deathbaba** [comment]
What about future releases? Will they work correctly? Or after releasing this workaround and next "correct" release we need to support both work-around and "correct" implementations?

**Comment by deathbaba** [comment]
What is exact problem this PR solves?

**Comment by gardster** [comment]
Yes they will. It solves routing problems (and fixes several routing_integration_tests by the way).

**Pull request closed without merging**
