### PR TITLE
Fix using mwm size types

### PR DESCRIPTION
**Pull request by syershov**

### CODE REVIEW

**Comment by syershov** [comment]
DUDE JTTP

**Comment by bykoianko** [comment]
Не собирается: 
/home/rootuser/workspace/GitHubWatchdog/BUILD_MODE/release/label/Linux/omim/qt/search_panel.cpp:230:67: error: no type named 'TLocalAndRemoteSize' in namespace 'storage'; did you mean simply 'TLocalAndRemoteSize'?
  auto const progressChanged = [](storage::TCountryId const & id, storage::TLocalAndRemoteSize const & sz)

**Comment by syershov** [comment]
Ага, спасибо.

**Comment by syershov** [comment]
@bykoianko PTAL

**Comment by syershov** [comment]
DUDE JTTP

**Comment by syershov** [comment]
DUDE JTTP

**Comment by bykoianko** [comment]
Теперь осталось сборку под iOS починить:
/Users/jenkins/root/workspace/GitHubWatchdog/BUILD_MODE/release/label/ios/omim/iphone/Maps/Classes/Framework/MWMFrameworkObservers.h:28:64: error: expected a type
- (void)processCountry:(TCountryId const &)countryId progress:(TLocalAndRemoteSize const &)progress;

**Comment by syershov** [comment]
DUDE JTTP

**Comment by igrechuhin** [comment]
LGTM

**Comment by bykoianko** [comment]
LGTM

**Pull request merged**
