### PR TITLE
Android adaptive icons (Android 8.0+)

### PR DESCRIPTION
**Pull request by CasperSchroder**
This change adds adaptive icons for the app on android machines running 8.0 or above. This solves issue #10223 and updates the look and feel of the icon to the android 8.0+ standards.

It was tested using the android-google-beta apk and the and the android-web-beta apk on both the emulated Nexus 5X with android 9.0 (included in android studio) and a Wileyfox Swift running LineageOS 14.1 (android 7.1.2)

The new icon looks like this and "jiggles" as expected:
image

The Wileyfox properly shows the legacy icon.

(I have already signed the CLA)

### CODE REVIEW

**Comment by mapsmetest** [comment]
Can one of the admins verify this patch?

**Comment by MarkHaakman** [comment]
I've also signed the CLA.

**Comment by rokuz** [comment]
Hi, thank you for the contribution. Since you've modified images, we can't merge the request until our designer approve it. It can take a time.

**Comment by alexzatsepin** [comment]
Hi guys,

Our designer made appropriate image resources and we implemented adaptive icon https://github.com/mapsme/omim/pull/10865 basing on your pull request. Thanks again for your contribution. Now, current pull request might be closed.

**Pull request closed without merging**
