### PR TITLE
Using make_unique instead of new for indexer.

### PR DESCRIPTION
**Pull request by bykoianko**
@mpimenov PTAL

### CODE REVIEW

**Comment by bykoianko** [comment]
@mpimenov Как и договаривались поправил во все indexer. Кроме `FeaturesOffsetsTable`. У `FeaturesOffsetsTable` закрытый конструктор.

**Comment by bykoianko** [comment]
@mpimenov PTAL

**Review by mpimenov — APPROVED** [review]
LGTM

**Comment by mpimenov** [comment]
JTALL

**Comment by bykoianko** [comment]
Андроид не собрался по причинам не связанным с роутингом:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':lintVitalWebBeta'.
> Could not resolve all dependencies for configuration ':googleDebugRuntimeClasspath'.
   > Could not determine artifacts for com.my.tracker:mytracker-sdk:1.5.3: Skipped due to earlier error

Как впрочем и iOS:

Error when executing always post condition:
java.io.IOException: Failed to extract /Volumes/ExtSSD/jenkins-root/workspace/iOS@2/transfer of 1 files

@mpimenov PTAL

**Pull request merged**
