### PR TITLE
[] Fixes to .clang-format.

### PR DESCRIPTION
**Pull request by ygorshenin**

### CODE REVIEW

**Comment by ygorshenin** [comment]
Requires clang-format 3.9

**Comment by ygorshenin** [comment]
Therefore, if you're using clang-format, please, do
```
brew upgrade clang-format
```

**Comment by mpimenov** [comment]
Will this preserve the block structure of includes and only sort inside blocks?

**Comment by ygorshenin** [comment]
Only when blocks are separated by blank lines.

06 июля 2016 г. 9:33 пользователь "mpimenov" <notifications@github.com>
написал:

**Comment by mpimenov** [comment]
LGTM

**Comment by mpimenov** [comment]
@therearesomewhocallmetim PTAL

**Comment by therearesomewhocallmetim** [comment]
LGTM

**Pull request merged**
