### PR TITLE
Fixed CMake builds on some platforms

### PR DESCRIPTION
**Pull request by rokuz**

### CODE REVIEW

**Comment by rokuz** [comment]
DUDE JTTP

**Comment by mapsmetest** [comment]
GitHub Watchdog

**Comment by mapsmetest** [comment]
GitHub Watchdog

**Comment by mapsmetest** [comment]
GitHub Watchdog Failure http://angola.mapsme.mail.msk:8080/job/GitHubWatchdog/

**Comment by mapsmetest** [comment]
Build triggered. sha1 is merged.

**Comment by mapsmetest** [comment]
Build started sha1 is merged.

**Comment by mapsmetest** [comment]
GitHub Watchdog Failure http://angola.mapsme.mail.msk:8080/job/GitHubWatchCat/
 No test results found.

**Comment by greshilov** [comment]
JTTP DUDE

**Comment by greshilov** [comment]
LGTM

**Pull request merged**
