### PR TITLE
[android] target sdk 28 support

### PR DESCRIPTION
**Pull request by alexzatsepin**
https://jira.mail.ru/browse/MAPSME-11555

### CODE REVIEW

**Comment by alexzatsepin** [comment]
Depends on https://github.com/mapsme/omim-private/pull/121

**Comment by ToshUxanoff** [comment]
JTGITR

**Comment by alexzatsepin** [comment]
@burivuh PTAL

**Comment by burivuh** [comment]
We can merge to 94 branch

**Pull request merged**
