### PR TITLE
[routing] Fixing routing integration tests and routing quality tests for maps 19.07.2019.

### PR DESCRIPTION
**Pull request by bykoianko**
Поправил outing integration tests and routing quality tests. Пока не мержим. Ждем релизной карты.

image

image

image

### CODE REVIEW

**Comment by bykoianko** [comment]
JTRIT

**Comment by bykoianko** [comment]
JTRQ

**Comment by bykoianko** [comment]
JTRIT

**Comment by bykoianko** [comment]
JTRQ

**Comment by ToshUxanoff** [comment]
JTRIT

**Comment by ToshUxanoff** [comment]
JTRQ

**Comment by ToshUxanoff** [comment]
JTRIT

**Comment by ToshUxanoff** [comment]
JTRIT

**Comment by ToshUxanoff** [comment]
JTRIT

**Comment by ToshUxanoff** [comment]
JTRIT

**Comment by ToshUxanoff** [comment]
JTRIT

**Pull request merged**
