### PR TITLE
[Geometry] Renamed TAltitude to Altitude.

### PR DESCRIPTION
**Pull request by mesozoic-drones**
Refactoring of old-style naming of `TAltitude` (TAltitudes)  to `Altitude` (Altitudes).

### CODE REVIEW

**Comment by mesozoic-drones** [comment]
JTALL

**Comment by bykoianko** [comment]
JTGITR

**Comment by bykoianko** [comment]
JTSIT

**Comment by bykoianko** [comment]
JTRIT

**Comment by bykoianko** [comment]
JTRQ

**Comment by mesozoic-drones** [comment]
JTRIT

**Pull request merged**
