### PR TITLE
Fix case typo in translation

### PR DESCRIPTION
**Pull request by frodrigo**

### CODE REVIEW

**Comment by frodrigo** [comment]
Redo commit to set translation in the right file.

**Comment by therearesomewhocallmetim** [comment]
JTTP FORMAT

**Comment by frodrigo** [comment]
> JTTP FORMAT
Sorry, no idea what mean JTTP FORMAT, I should do or fix something ?

**Comment by therearesomewhocallmetim** [comment]
No, it is a command for our Continuous integration system. Please, pay no attention to it.

**Comment by Zverik** [comment]
Could you please sign the [CLA](http://maps.me/cla/)?

**Comment by frodrigo** [comment]
I just sign it, but like @fijemax I need a corporate CLA for Mapotempo

**Comment by Zverik** [comment]
Thanks for this PR. I'll look into corporate CLAs, sorry there isn't one yet.

**Pull request merged**
