### PR TITLE
[coding] [geometry] Refactored geometry serialization.

### PR DESCRIPTION
**Pull request by mpimenov**
This PR moves all the code related to geometry serialization from indexer/ and coding/ to a single place, namely coding/geometry_coding.{c,h}pp.

### CODE REVIEW

**Comment by mpimenov** [comment]
JTTP

**Comment by rokuz** [comment]
DUDE JTTP

**Comment by mpimenov** [comment]
JTTP

**Comment by mpimenov** [comment]
JTTP

**Comment by mpimenov** [comment]
JTTP

**Pull request merged**
