### PR TITLE
[schemes] [ios] Updated Xcode schemes.

### PR DESCRIPTION
**Pull request by igrechuhin**

### CODE REVIEW

**Comment by greshilov** [comment]
DUDE JTTP

**Comment by mapsmetest** [comment]
GitHub Watchcat

**Comment by mapsmetest** [comment]
GitHub Watchcat

**Comment by mapsmetest** [comment]
GitHub Watchcat Failure http://angola.mapsme.mail.msk:8080/job/GitHubWatchCat/
 No test results found.

**Comment by greshilov** [comment]
It works, thanks!

**Pull request merged**
