### PR TITLE
Remove tomcrypt and old files

### PR DESCRIPTION
**Pull request by syershov**

### CODE REVIEW

**Comment by syershov** [comment]
DUDE JTTP

**Comment by mapsmetest** [comment]
[ 76%] Linking CXX executable ../../platform_tests
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Alohalytics", referenced from:
      objc-class-ref in libplatform.a(platform_mac.mm.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [platform_tests] Error 1
make[1]: *** [platform/platform_tests/CMakeFiles/platform_tests.dir/all] Error 2
make: *** [all] Error 2

**Comment by mapsmetest** [comment]
Плюс вочдог не прошел.

**Comment by syershov** [comment]
DUDE JTTP

**Comment by syershov** [comment]
DUDE JTTP

**Comment by Zverik** [comment]
Под линуксом собралось.

**Comment by syershov** [comment]
DUDE JTTP

**Pull request merged**
