### PR TITLE
[qt] Map layers for desktop application.

### PR DESCRIPTION
**Pull request by mesozoic-drones**
Map layers selection instead of only one button with traffic:
Screenshot 2020-03-24 at 15 02 19

Before PR:
Screenshot 2020-03-24 at 16 32 26

Traffic layer activated:
Screenshot 2020-03-24 at 15 03 10

Isolines layer activated:
Screenshot 2020-03-24 at 15 03 32

Transit layer activated:
Screenshot 2020-03-24 at 15 03 53

### CODE REVIEW

**Comment by bykoianko** [comment]
JTA

**Comment by mesozoic-drones** [comment]
JTALL

**Comment by ToshUxanoff** [comment]
JTANDROID

**Comment by ToshUxanoff** [comment]
JTANDROID

**Pull request merged**
