### PR TITLE
Boost 1.59.

### PR DESCRIPTION
**Pull request by deathbaba**

### CODE REVIEW

**Comment by deathbaba** [comment]
JTTP

**Comment by mapsmetest** [comment]
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

**Comment by deathbaba** [comment]
JTTP

**Comment by therearesomewhocallmetim** [comment]
JTTP

**Comment by therearesomewhocallmetim** [comment]
JTTP

**Comment by therearesomewhocallmetim** [comment]
JTTP

**Comment by therearesomewhocallmetim** [comment]
JTTP

**Comment by deathbaba** [comment]
@therearesomewhocallmetim Looks like submodules are not updated for the build, and it fails. Please update jenkins to run ```git submodule update --init --recursive``` after any checkout.

**Comment by therearesomewhocallmetim** [comment]
JTTP

**Comment by deathbaba** [comment]
JTTP @ygorshenin PTAL please.

**Comment by ygorshenin** [comment]
LGTM, но #include <limits> нужно добавить обязательно. Может сфейлится сборка при другом тулчейне.

**Comment by deathbaba** [comment]
@ygorshenin Добавил инклуд. PTAL please.

**Comment by deathbaba** [comment]
Добавил инклуд.

**Comment by ygorshenin** [comment]
LGTM

**Pull request merged**
