### PR TITLE
[release-72-carthage] [ios] Moved frameworks to Carthage.

### PR DESCRIPTION
**Pull request by igrechuhin**
Alamofire
AlamofireImage
Pushwoosh

### CODE REVIEW

**Comment by igrechuhin** [comment]
DUDE JTTP

**Comment by igrechuhin** [comment]
DUDE JTTP

**Comment by therearesomewhocallmetim** [comment]
DUDE JTTP

**Comment by therearesomewhocallmetim** [comment]
DUDE JTTP

**Pull request merged**
