### PR TITLE
[ios] Fixed compilation.

### PR DESCRIPTION
**Pull request by VladiMihaylenko**

### CODE REVIEW

**Comment by VladiMihaylenko** [comment]
DUDE JTTP

**Comment by mapsmetest** [comment]
Build started sha1 is merged.

**Comment by therearesomewhocallmetim** [comment]
DUDE JTTP

**Comment by mapsmetest** [comment]
Build started sha1 is merged.

**Comment by mapsmetest** [comment]
GitHub Watchdog Failure http://angola.mapsme.mail.msk:8080/job/GitHubWatchdog/

**Pull request merged**
