### PR TITLE
Diff stage fix

### PR DESCRIPTION
**Pull request by burivuh**

### CODE REVIEW

**Comment by mpimenov** [comment]
Why 2 commits?

**Comment by burivuh** [comment]
First one is because I'm a bit noob. You may ignore it. Actual change between master and this PR is only in the second one

**Comment by mpimenov** [comment]
Could you please squash the commits (git rebase -i master, mark the 2nd one as "fixup")

**Comment by burivuh** [comment]
Looks like it is much simpler to create a new PR
https://github.com/mapsme/omim/pull/13963

**Pull request closed without merging**
