### PR TITLE
[ios][drape] Added widgets layout routine.

### PR DESCRIPTION
**Pull request by igrechuhin**

### CODE REVIEW

**Comment by mapsmetest** [comment]
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

**Comment by rokuz** [comment]
LGTM

**Comment by igrechuhin** [comment]
@VladiMihaylenko PTAL

**Comment by vng** [comment]
LGTM

**Pull request merged**
