### PR TITLE
 [android] Removed location predictor

### PR DESCRIPTION
**Pull request by alexzatsepin**
https://jira.mail.ru/browse/MAPSME-3861
@bykoianko @mpimenov @rokuz @goblinr PTAL

### CODE REVIEW

**Comment by mpimenov** [comment]
А map/framework.{c,h}pp?

**Comment by alexzatsepin** [comment]
> А map/framework.{c,h}pp?

Those files are used by IOS yet and cannot be deleted. Also, I asked QA to test this PR https://jira.mail.ru/browse/MAPSME-3861, so I put DNM tag.

**Comment by bykoianko** [comment]
DUDE JTTP

**Comment by bykoianko** [comment]
DUDE JTTP

**Comment by bykoianko** [comment]
В целом LGTM, но пускай соберется сначала.

**Comment by therearesomewhocallmetim** [comment]
DUDE JTTP

**Comment by therearesomewhocallmetim** [comment]
DUDE JTTP

**Comment by alexzatsepin** [comment]
@mpimenov PTAL

**Comment by mpimenov** [comment]
LGTM

**Pull request merged**
