### PR TITLE
[transit] Fix for world feed cmakelists in tests.

### PR DESCRIPTION
**Pull request by mesozoic-drones**

### CODE REVIEW

**Comment by mesozoic-drones** [comment]
JTLINUX

**Comment by mesozoic-drones** [comment]
JTLINUX

**Comment by mesozoic-drones** [comment]
JTLINUX

**Comment by mesozoic-drones** [comment]
JTLINUX

**Comment by mesozoic-drones** [comment]
LINUXGCC

**Comment by tatiana-yan** [comment]
JTLINUXGCC

**Pull request merged**
