### PR TITLE
[build] Build fix for libstdc++.

### PR DESCRIPTION
**Pull request by therearesomewhocallmetim**
Tried to cherry-pick Yura's fix from Master.

### CODE REVIEW

**Comment by therearesomewhocallmetim** [comment]
DUDE JTTP

**Comment by therearesomewhocallmetim** [comment]
DUDE JTTP

**Comment by therearesomewhocallmetim** [comment]
DUDE JTTP

**Comment by ygorshenin** [comment]
LGTM

**Comment by therearesomewhocallmetim** [comment]
DUDE JTTP

**Comment by therearesomewhocallmetim** [comment]
DUDE JTTP

**Comment by syershov** [comment]
LGTM

**Pull request merged**
