### PR TITLE
Updated Polish translation

### PR DESCRIPTION
**Pull request by psokol**
I added some missing strings and in general started to improve whole translation.

### CODE REVIEW

**Comment by therearesomewhocallmetim** [comment]
Dear Piotr, 
Could you explain why you made the changes you made, why your variants are better than the original ones.

Also, the pull requests modifying the `strings.txt` file should follow the following requirements: after you have made any changes to `strings.txt`, please, run the `tools/python/find_untranslated_strings.py` script. Apart from other things, it will autoformat the strings.txt file. After that, commit the `strings.txt` file. Then, please, run the `tools/unix/generate_localizations.sh` script, and commit the generated strings. As the result, there should be two commits in total: one with the modified strings.txt, and one with the generated resources.

Best regards, 
Timofey

**Comment by psokol** [comment]
Dear Timofey,

Thank you for detailed hints. I'm quite new to git and github so I'm still learning. Please comment if is everything right now.

About the translation: in general replaced strings are shorter (it's alway better to have shorter messages on the phone app) and more accurately translated. I have quite big experience with translating linux and android apps, so I always translate with well known rules (i.e. use some polite expressions, certain verb forms and words translations) to get consistent and clear user interface.
I always try to support open software I use and I hope my translation skills will be helpful.

Best regards,
Piotr

**Comment by Zverik** [comment]
Hi Piotr,

Could you please sign [the CLA](http://maps.me/cla/), so we could use your contributions?

**Comment by psokol** [comment]
Done

**Comment by therearesomewhocallmetim** [comment]
Dear Piotr,

I pulled your changes in a different pull request. Thank you very much for your contribution.

Best regards, 
Timofey

**Pull request closed without merging**
