### PR TITLE
Fixed an out-of-bounds access.

### PR DESCRIPTION
**Pull request by mpimenov**

### CODE REVIEW

**Comment by mpimenov** [comment]
@bykoianko The only place where this function is used is routing/turns_generator.cpp. Do we even need it?

**Comment by vng** [comment]
LGTM

**Comment by ygorshenin** [comment]
LGTM

**Comment by bykoianko** [comment]
Yes. We need to for cases when a name of a road contains a kilometer(mile) counter. For example, "MKAD, 60 km", "MKAD, 59 km".

LGTM

**Pull request merged**
