### PR TITLE
Fix Spanish sound strings

### PR DESCRIPTION
**Pull request by k1wiosm**
I fixed some of the Spanish sound strings on `data/sound-strings/es.json/localize.json`.

### CODE REVIEW

**Comment by deathbaba** [comment]
CC @bykoianko

**Comment by p2kmgcl** [comment]
I was going to modify [these files](https://github.com/mapsme/omim/tree/master/sound/tts) also for the Spanish translation. Can I make another pull request or those files are incorrect?

**Comment by deathbaba** [comment]
These files are correct. As far as I know, csv is the source file, everything else is generated out of it. CC @bykoianko

**Comment by p2kmgcl** [comment]
@deathbaba but what about the json files? should I modify them too? Those json files don't appear on the wiki.

**Comment by deathbaba** [comment]
json files are generated out of txt files, and txt files are generated out of csv files. So it's better to modify csv, and then regenerate everything.

@bykoianko can you please explain it in more details? May be update a wiki page about it?

**Comment by p2kmgcl** [comment]
@deathbaba :ok_hand:, so @k1wiosm are you going to modify this pull request or should I start a new one?

**Comment by deathbaba** [comment]
I suppose it would be better to start a new one and do it in a right way, incorporate all summary changes and modify all needed source files.

**Comment by p2kmgcl** [comment]
@deathbaba ok I am gonna start that one and refer this

**Comment by k1wiosm** [comment]
I guess I should close this one, right?

**Comment by deathbaba** [comment]
Yes, and thanks for initiating it :+1:

**Pull request closed without merging**
