### PR TITLE
[omim][drape] Changed usermark deactivate logic.

### PR DESCRIPTION
**Pull request by igrechuhin**

### CODE REVIEW

**Comment by VladiMihaylenko** [comment]
LGTM

**Comment by igrechuhin** [comment]
@yunikkk @rokuz @vng PTAL

**Comment by mapsmetest** [comment]
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

**Comment by yunikkk** [comment]
LGTM

**Pull request merged**
