### PR TITLE
[android] Whats'new, new.

### PR DESCRIPTION
**Pull request by yunikkk**

### CODE REVIEW

**Comment by trashkalmar** [comment]
Надо бы удалить старые картинки и тексты.

**Comment by rugk** [comment]
Just a question: Can't you just use SVGs instead of many, many PNG images?

**Comment by trashkalmar** [comment]
@rugk yep. However in this case SVGs will be too large.

**Comment by rugk** [comment]
SVGs can scale to any size or do you mean the file size?

**Comment by trashkalmar** [comment]
Yes, file size. SVG are good for simple icons. But for complex images they are too huge and too slow.

**Comment by rugk** [comment]
And you cannot [minify](https://github.com/svg/svgo) them, so that they are small enough?

**Comment by trashkalmar** [comment]
Honestly, I do not know. Our designer may take a look. @igortomko

**Pull request merged**
