### PR TITLE
Added icons for Brussels metro

### PR DESCRIPTION
**Pull request by forthommel**
This PR intends to add the official icon for Brussels metro stations.

### CODE REVIEW

**Comment by forthommel** [comment]
Hi! Have you had any chance to look at this lately? :)

**Comment by rokuz** [comment]
@igortomko Проверь, пожалуйста, векторную графику и стили на корректность и соответствие нашим правилам

**Comment by Zverik** [comment]
Почему именно Брюссель?

**Comment by rokuz** [comment]
@forthommel Hi, thanks for your request. We've ordered a huge pack of subway icons for different cities. We're going to add it all together and of course consider your graphics.

**Comment by forthommel** [comment]
Hi @rokuz, @Zverik, thanks for your review! Let me know if you need any input when putting this all together.

**Pull request closed without merging**
