### PR TITLE
Fix boost minimal version to 1.59

### PR DESCRIPTION
**Pull request by greshilov**
I've caught error like this, when tried to build our project with boost ver. 1.58:
```
/*/omim/editor/feature_matcher.cpp:270:24: error: no member
      named 'is_empty' in namespace 'boost::geometry'
  if (boost::geometry::is_empty(their))
```
Hence minimal version is now 1.59.

### CODE REVIEW

**Comment by greshilov** [comment]
JCRT

**Comment by greshilov** [comment]
JCRT

**Comment by greshilov** [comment]
JCRT

**Comment by syershov** [comment]
We can install boost 1.54 or 1.64 on Centos6 and 1.66 on Centos7.

**Comment by greshilov** [comment]
JTRIT

**Comment by greshilov** [comment]
@bykoianko PTAL

**Pull request merged**
