### PR TITLE
added Tamil translations.

### PR DESCRIPTION
**Pull request by r0a0j0e0s0h**

### CODE REVIEW

**Comment by deathbaba** [comment]
Please make one pull request related to Tamil translations which contain different commits with changes in different files.

**Comment by r0a0j0e0s0h** [comment]
I am not sure if it is allowing to do pull request based on directory, I see the create button enabled only on per file basis. There are 4 files under sound/tts pertaining to the languages.

**Comment by deathbaba** [comment]
You should do it using command line git, not via web interface.

**Comment by deathbaba** [comment]
Please make one Pull Request with separate commits for every file (or put all changes into one commit).

**Pull request closed without merging**
