### PR TITLE
[drape] Removed dummy assert.

### PR DESCRIPTION
**Pull request by vng**

### CODE REVIEW

**Comment by mapsmetest** [comment]
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

**Comment by ygorshenin** [comment]
How about to remove it, not comment? This ASSERT() seems wrong as it fails on desktop debug build.

**Comment by rokuz** [comment]
LGTM

**Comment by ygorshenin** [comment]
LGTM

**Pull request merged**
