### PR TITLE
Adding two small islands missed in Taiwan.poly

### PR DESCRIPTION
**Pull request by kcwu**
https://www.openstreetmap.org/way/9216199 東碇島
https://www.openstreetmap.org/relation/3339702 烏坵鄉

### CODE REVIEW

**Comment by deathbaba** [comment]
Hi, have you already signed our CLA? http://maps.me/cla/

@Zverik can you please take a look?

**Comment by Zverik** [comment]
The new border seems legit.
LGTM after @kcwu signed CLA.

**Comment by kcwu** [comment]
Ah, I'd prefer not sign CLA for such simple patch. (Otherwise it may be long process with my employer)
Could you fix it yourself for those two islands?

**Comment by deathbaba** [comment]
Can you please tell us, which CLA sentences are worrying you and can lead to issues with an employer? May be we should revise it?

**Comment by kcwu** [comment]
Not about your CLA sentences. I'm just worrying the process of my employer :P

**Comment by Zverik** [comment]
You are signing as a private person, not an employee. The CLA just ensures you keep the rights to your contributions, and we get to use them however we need.

**Comment by kcwu** [comment]
Because my employer asked us they want to review any CLA we signed as a private person.

**Comment by Zverik** [comment]
Okay, I've done similar changes, also modifying the China border, in #1155.

**Pull request closed without merging**
