### PR TITLE
Unique commits in release-62x to master

### PR DESCRIPTION
**Pull request by bykoianko**
Уникальные коммиты из ветки release-62x на мастер.
@therearesomewhocallmetim Запусти п-та generate_style и сделай еще один коммит в этот PR. Т.е. в upstream/master-unique-commits-of-release-62x_v2

### CODE REVIEW

**Comment by bykoianko** [comment]
@Zverik @therearesomewhocallmetim и другие PTAL

**Comment by Zverik** [comment]
LGTM

**Comment by therearesomewhocallmetim** [comment]
Прогнал style_tests. Некоторые тесты упали. Надо разобраться, почему. 
Running style_symbols_consistency_test.cpp::Test_SymbolsConsistency
Test with map style MapStyleLight
Test with map style MapStyleDark
Symbols mismatch: style MapStyleDark , density ldpi , missed [19: olympic-airport-m olympic-bus-l olympic-bus-m olympic-cable-car-l olympic-cable-car-m olympic-cycle-l olympic-ship-l olympic-ship-m olympic-stadium-l olympic-stadium-main-l olympic-subway-l olympic-subway-m olympic-tourism-l olympic-train-m olympic-train-s olympic-tram-l olympic-tram-m olympic-view-l olympic-water-l ]
Symbols mismatch: style MapStyleDark , density mdpi , missed [19: olympic-airport-m olympic-bus-l olympic-bus-m olympic-cable-car-l olympic-cable-car-m olympic-cycle-l olympic-ship-l olympic-ship-m olympic-stadium-l olympic-stadium-main-l olympic-subway-l olympic-subway-m olympic-tourism-l olympic-train-m olympic-train-s olympic-tram-l olympic-tram-m olympic-view-l olympic-water-l ]
Symbols mismatch: style MapStyleDark , density hdpi , missed [19: olympic-airport-m olympic-bus-l olympic-bus-m olympic-cable-car-l olympic-cable-car-m olympic-cycle-l olympic-ship-l olympic-ship-m olympic-stadium-l olympic-stadium-main-l olympic-subway-l olympic-subway-m olympic-tourism-l olympic-train-m olympic-train-s olympic-tram-l olympic-tram-m olympic-view-l olympic-water-l ]
Symbols mismatch: style MapStyleDark , density xhdpi , missed [19: olympic-airport-m olympic-bus-l olympic-bus-m olympic-cable-car-l olympic-cable-car-m olympic-cycle-l olympic-ship-l olympic-ship-m olympic-stadium-l olympic-stadium-main-l olympic-subway-l olympic-subway-m olympic-tourism-l olympic-train-m olympic-train-s olympic-tram-l olympic-tram-m olympic-view-l olympic-water-l ]
Symbols mismatch: style MapStyleDark , density xxhdpi , missed [19: olympic-airport-m olympic-bus-l olympic-bus-m olympic-cable-car-l olympic-cable-car-m olympic-cycle-l olympic-ship-l olympic-ship-m olympic-stadium-l olympic-stadium-main-l olympic-subway-l olympic-subway-m olympic-tourism-l olympic-train-m olympic-train-s olympic-tram-l olympic-tram-m olympic-view-l olympic-water-l ]
Symbols mismatch: style MapStyleDark , density 6plus , missed [19: olympic-airport-m olympic-bus-l olympic-bus-m olympic-cable-car-l olympic-cable-car-m olympic-cycle-l olympic-ship-l olympic-ship-m olympic-stadium-l olympic-stadium-main-l olympic-subway-l olympic-subway-m olympic-tourism-l olympic-train-m olympic-train-s olympic-tram-l olympic-tram-m olympic-view-l olympic-water-l ]
Test with map style MapStyleClear
FAILED
style_tests/style_symbols_consistency_test.cpp:97 TEST(res)
Test took 538 ms

1  tests failed:
style_symbols_consistency_test.cpp::Test_SymbolsConsistency
Some tests FAILED.

**Comment by Zverik** [comment]
Понятно, почему: олимпийские значки сделаны только для светлого стиля. В тёмном они не смотрятся, да и не нужны особо. Предлагаю пока оставить так.

**Comment by therearesomewhocallmetim** [comment]
Илья, у нас тогда мастер получится красным. 
Мы можем просто продублировать иконки дневного стиля в ночной и классический?

**Comment by bykoianko** [comment]
И не только мастер. Сразу после мержа этого PR у нас будет сделана ветка release-63. И она тоже будет красная. Если это норм, то может добавим коммит в этот PR, который чинит тесты?

**Comment by Zverik** [comment]
Хорошо, тогда просто скопируй `styles/clear/style-light/symbols/olympic-*` в `styles/clear/style-night/symbols` и запусти `generate_styles.sh` заново.

**Comment by therearesomewhocallmetim** [comment]
Ran the script twice because the results of the execution differ.

**Comment by bykoianko** [comment]
DUDE JTTP

**Comment by therearesomewhocallmetim** [comment]
LGTM

**Comment by bykoianko** [comment]
LGTM

**Comment by Zverik** [comment]
Странно, я же фиксил недетерминированность запуска skin_generator...

LGTM

**Pull request merged**
