### PR TITLE
[ios] Updated no wifi alert display logic.

### PR DESCRIPTION
**Pull request by igrechuhin**
https://jira.mail.ru/browse/MAPSME-612
@VladiMihaylenko @bykoianko @syershov PTAL

### CODE REVIEW

**Comment by VladiMihaylenko** [comment]
LGTM

**Comment by bykoianko** [comment]
LGTM

**Comment by igrechuhin** [comment]
@VladiMihaylenko @syershov PTAL

**Comment by syershov** [comment]
LGTM

**Pull request merged**
