### PR TITLE
[categories] Swahili translations from our Peace Corps friends.

### PR DESCRIPTION
**Pull request by deathbaba**
This requests is a fixed version of #2026.
@choquette33 for correct Swahili support we need also translations for strings.txt file. Our wiki has more details: https://github.com/mapsme/omim/wiki/strings.txt

Not all translations are present, we have added several new types.

I would suggest to take strings.txt from new-search branch, as it's more fresh and under active development now ( https://github.com/mapsme/omim/blob/new-search/strings.txt )

### CODE REVIEW

**Comment by Zverik** [comment]
I don't see any autocompletion numbers in these strings. Are they needed?

Also, without strings.txt translations these I pretty useless, I presume?

**Comment by deathbaba** [comment]
No, they are not completely useless - Place Page on a map will have a correct translation.

**Comment by Zverik** [comment]
But does the app support Swahili? Shouldn't the language be added to some list?

**Comment by deathbaba** [comment]
I’ll do it on a new-search branch first and then pull needed commits into the master.

**Comment by Zverik** [comment]
What do you mean? This PR is for the master branch.
As for the question, I meant, do we have a list of supported languages somewhere, so if we don't add `sw` to it, this translation won't be used?

**Comment by deathbaba** [comment]
Ok, ok, here is it, I’ve added in a new commit.

**Comment by choquette33** [comment]
Ok- I'll take a look at this one: https://github.com/mapsme/omim/blob/new-search/strings.txt

**Pull request merged**
