### PR TITLE
Update car.lua; Add Dutch maxspeed limits

### PR DESCRIPTION
**Pull request by hvdwolf**
Update car.lua; Add Dutch maxspeed limits

### CODE REVIEW

**Comment by deathbaba** [comment]
@gardster please check it

**Comment by gardster** [comment]
Add same records to the osrm-backend/profile.lua file, please.

**Comment by hvdwolf** [comment]
I just added the 3 lines to the profile.lua as well. Sorry for omitting this in first instance

**Comment by gardster** [comment]
LGTM

**Comment by gardster** [comment]
@hvdwolf thank you for your contribution.

**Pull request merged**
