### PR TITLE
[search] Fixes to features collector tool.

### PR DESCRIPTION
**Pull request by ygorshenin**
@mpimenov PTAL

### CODE REVIEW

**Comment by deathbaba** [comment]
DUDE JTTP
LGTM

**Comment by syershov** [comment]
LGTM

**Comment by mpimenov** [comment]
LGTM

**Comment by ygorshenin** [comment]
Merge, please. The jenkins failure is not related to this CL.

**Comment by ygorshenin** [comment]
@deathbaba merge please?

**Pull request merged**
