### PR TITLE
Updated and fixed Polish strings

### PR DESCRIPTION
**Pull request by strebski**
More natural and male/female neutral forms

### CODE REVIEW

**Comment by bykoianko** [comment]
Thank you, but to make it work you need
- to install twin
- to run https://github.com/mapsme/omim/blob/master/tools/unix/generate_localizations.sh
then you see some difference in: https://github.com/mapsme/omim/tree/master/data/sound-strings
- then to make a new commit with the diff.

**Comment by mpimenov** [comment]
@bykoianko I think we can do this part ourselves.

**Comment by bykoianko** [comment]
> @bykoianko I think we can do this part ourselves.

All right. I did a PR using the commit by Mr. @strebski 

https://github.com/mapsme/omim/pull/11700

@strebski @mpimenov PTAL

**Comment by bykoianko** [comment]
Thank you @strebski. I put your commit to #11700.

**Pull request closed without merging**
