### PR TITLE
Fix italian translation

### PR DESCRIPTION
**Pull request by Mannivu**
Italian translation of "Car shop" was wrong

### CODE REVIEW

**Comment by mapsmetest** [comment]
Can one of the admins verify this patch?

**Comment by mpimenov** [comment]
Hello. Please sign the CLA: https://maps.me/cla/

**Comment by mpimenov** [comment]
Could you please also check this translation in https://github.com/mapsme/omim/blob/master/strings.txt ?

**Comment by Mannivu** [comment]
> Please sign the CLA: https://maps.me/cla/

Done

**Comment by Mannivu** [comment]
> Could you please also check this translation in https://github.com/mapsme/omim/blob/master/strings.txt ?

I think that string.txt isn't affected by this edit.

**Pull request merged**
