### PR TITLE
[Android] Create strings.xml for Farsi language (Persian)

### PR DESCRIPTION
**Pull request by imanmoghimiq30**

### CODE REVIEW

**Comment by mpimenov** [comment]
@imanmoghimiq30 The correct way to update the translations showed in the UI is to edit strings.txt. The xml files are then generated by running a script. For a detailed description refer to https://github.com/mapsme/omim/wiki/strings.txt

**Comment by imanmoghimiq30** [comment]
@mpimenov Hi
But I translated it a few months ago and nothing happened
Who should run the code؟

**Comment by mpimenov** [comment]
@imanmoghimiq30 What did you expect do happen?

Please read the link I provided. Here is an excerpt:

> After you edit strings.txt, please commit your changes (suggested commit message is [strings] Fixed translations), and then run tools/unix/generate_localization.sh script from repository root.

**Comment by imanmoghimiq30** [comment]
sorry my friends. I should close this and work on string file

**Pull request closed without merging**
