### PR TITLE
[styles] bus stops z-index

### PR DESCRIPTION
**Pull request by keksikex**
Changed bus stops z-index and toilets z-index (resolved problem with the toilet in AV Daily)

### CODE REVIEW

**Comment by mapsmetest** [comment]
Can one of the admins verify this patch?

**Comment by rokuz** [comment]
JTA

**Comment by rokuz** [comment]
Тесты по стилям не прошли:
style_tests/classificator_tests.cpp:224 TEST(minmax.second < mm.first) 16477 16447 Priority bug on zoom 16 group 1 : [2: amenity-bench amenity-shelter ] 16477 16477 vs [5: highway-bus_stop amenity-bus_station railway-station railway-halt railway-tram_stop ] 16447 16559

Есть пересечение по z-уровню. Запускай плиз тесты из Designer Tool :)

**Comment by rokuz** [comment]
JTA

**Comment by mapsmetest** [comment]
Analysed

**Pull request merged**
