### PR TITLE
Fix platform tests

### PR DESCRIPTION
**Pull request by syershov**

### CODE REVIEW

**Comment by syershov** [comment]
DUDE
JTTP

**Comment by ygorshenin** [comment]
LGTM, but please delay merge before Jenkins approval.

**Comment by syershov** [comment]
DUDE
JTTP

**Comment by therearesomewhocallmetim** [comment]
DUDE JTTP

**Comment by therearesomewhocallmetim** [comment]
DUDE
JTTP

**Comment by syershov** [comment]
DUDE
JTTP

**Comment by therearesomewhocallmetim** [comment]
DUDE JTTP

**Comment by Zverik** [comment]
LGTM

**Pull request merged**
