### PR TITLE
[search] A compiler for faster processing of hotel filters.

### PR DESCRIPTION
**Pull request by ygorshenin**
@mpimenov PTAL

### CODE REVIEW

**Comment by mpimenov** [comment]
s/VM/Virtual machine for filters/
or
s/VM/A compiler for filters/

**Comment by mpimenov** [comment]
Do you have any benchmarks supporting this PR?

**Comment by ygorshenin** [comment]
No, I have no benchmarks.

**Comment by mpimenov** [comment]
Could you please provide some benchmarks?
Note that our testing facility measures time so a sufficiently large test should suffice.

**Comment by ygorshenin** [comment]
Seems that on moderate-size requests on real maps this approach is 1.5 times slower than the previous one. Let's close the PR.

**Pull request closed without merging**
