### PR TITLE
[build-fix] [ios] Fixed build.

### PR DESCRIPTION
**Pull request by igrechuhin**

### CODE REVIEW

**Comment by igrechuhin** [comment]
DUDE JTTP

**Comment by therearesomewhocallmetim** [comment]
DUDE JTTP

**Comment by igrechuhin** [comment]
DUDE JTTP

**Comment by therearesomewhocallmetim** [comment]
DUDE JTTP

**Comment by therearesomewhocallmetim** [comment]
LGTM

**Pull request merged**
