### PR TITLE
Extends the navigation panel ui in landscape mode for the large layout-w1020dp.

### PR DESCRIPTION
**Pull request by fijemax**
I extended the ui navigation panel for large android screen.
Before : 
device-2016-09-12-1
After : 
device-2016-09-12-2

### CODE REVIEW

**Comment by mpimenov** [comment]
@igortomko @alexzatsepin

**Comment by igortomko** [comment]
Do not touch navigation on tablets, now

**Comment by fijemax** [comment]
Thank you for your reply.
Have you planned to change this ?

**Comment by burivuh** [comment]
Hi!

Yes, codebase is currently changing. Let's return to this after upcoming
release

**Pull request closed without merging**
