### PR TITLE
[testing] Renamed pedestrian_routing_benchmarks -> pedestrian_routing_tests

### PR DESCRIPTION
**Pull request by kshalnev**
Для упрощения автоматизации запуска тестов переименовал тест pedestrian_routing_benchmark в pedestrian_routing_tests - тесты запускаются по суффиксу _tests

### CODE REVIEW

**Comment by mapsmetest** [comment]
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

**Comment by kshalnev** [comment]
Тимофей, PTAL

**Comment by gardster** [comment]
LGTM

**Comment by therearesomewhocallmetim** [comment]
LGTM

**Pull request merged**
