### PR TITLE
Improve Swedish translation

### PR DESCRIPTION
**Pull request by manucheri**
Change: Get --> Ge
"Get" means goat in Swedish. Ge means "give", which is correct.

Also add translation for Compass calibration.

### CODE REVIEW

**Comment by mpimenov** [comment]
Please run tools/unix/generate_localizations.sh and add the generated strings as a separate commit.

**Comment by manucheri** [comment]
Done. It seems like it also affected some other translations (which I haven't touched). Should I perhaps only include the changes to the Swedish parts?

**Comment by deathbaba** [comment]
Please rebase request on top of the freshest master branch and leave only your changes in generated content.

**Comment by manucheri** [comment]
Done. Rebased, and fixed so I only commit generated strings related to my changes.

**Comment by deathbaba** [comment]
Thanks!

**Pull request merged**
