### PR TITLE
Mapsme 49 settings refactoring

### PR DESCRIPTION
**Pull request by nbaulesglobalsolutions**
How do you add-in or improve you pull request?

### CODE REVIEW

**Comment by matkoniecz** [comment]
> How do you add-in or improve you pull request?

One may push additional commits to branch of your PR.

**Comment by alexzatsepin** [comment]
@nbaulesglobalsolutions what is the purpose of this PR? It seems like base branch was chosen incorrectly or something else, because it consists only already merged commits and your commit is not presented in list.

**Comment by mapsmetest** [comment]
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

**Comment by matkoniecz** [comment]
@mapsme this PR is apparently mistake and probably may be safely closed.

**Pull request closed without merging**
