### PR TITLE
fix typo in japanese string

### PR DESCRIPTION
**Pull request by smellman**
Fix japanese translate string in "downloader_delete_routing".

### CODE REVIEW

**Comment by bykoianko** [comment]
We make two commits for such PRs. The first one strings.txt and the second one for android/res/values-*/strings.xml and for iphone/Maps/*.lproj/Localizable.strings.
So split it into commits please.

**Comment by deathbaba** [comment]
Hi Taro and welcome! I have two comments:
1. You need to sign CLA once before contributing: http://maps.me/cla/
2. We usually split translations into two commits: one for strings.txt and second for re-generated strings. This helps to avoid crazy merges in some cases.

**Comment by trashkalmar** [comment]
To generate platform strings (strings.xml and *.lproj) you should run tools/unix/generate_localizations.sh

**Comment by smellman** [comment]
Thanks, I will check it but I want a few days to check CLA document because difficult to read long English document for me.

**Comment by mapsmetest** [comment]
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

**Comment by deathbaba** [comment]
@smellman Hi! Is CLA ok for you?

**Comment by smellman** [comment]
I just sign CLA and create new pull request #132

**Pull request closed without merging**
