### PR TITLE
[strings] Add Amharic translation

### PR DESCRIPTION
**Pull request by fuadj**

### CODE REVIEW

**Comment by Zverik** [comment]
Please remove the second commit, it doesn't change anything related to your work. And please sign [the CLA](http://maps.me/cla/) so we could use your edits.

**Comment by fuadj** [comment]
When trying to sign the CLA I am getting 
_**You did not fill all fields correctly.
Please do that again.**_
And also, how do i delete the second commit. Do i do a hard reset and do a pull request again. Sorry to ask but it is my first time.

**Comment by Zverik** [comment]
Did you type "I AGREE" in uppercase letters?
To delete the last commit, run `git rebase -i HEAD~2` and delete the second line, with "Generated translation". Then do `git push --force origin amharic_translation`

**Comment by fuadj** [comment]
And btw, Maps.ME is a life saver. I use it every day and especially in Ethiopia where the internet is costly. I am trying to bundle the App with the map of Ethiopia baked-in so I can easily give it to people because people still need to download ~20MB to start using it. But I know that leads to problems with the map being outdated. What would you say is the best way to go about it.

**Comment by fuadj** [comment]
Yes i am writing I AGREE, infact when i don't it displays 
_**Please type "I AGREE" into the signature field.**_

**Comment by fuadj** [comment]
signiture

**Comment by fuadj** [comment]
I've signed the [CLA](http://maps.me/cla/),
The problem was with "Github Account", it only wants the part after github.com/ (i.e: your github profile). I think it should be stated as such.

**Comment by mapsmetest** [comment]
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

**Comment by mpimenov** [comment]
+@burivuh 

@fuadj 
1. Please rebase your branch to master: there are conflicts that prevent the merging.
2. Consider translating data/categories.txt if you want the search to work for popular categories, such as food and hotels.
3. While we can merge this into the repository, it seems that we cannot guarantee that the store versions will include Amharic in the near future.

**Comment by fuadj** [comment]
I rebased and pushed it, now it says the pull request is closed. Is it okay? Sorry to ask it is my first time doing this.

**Comment by mpimenov** [comment]
No, something went wrong.
It says that there are no new commits on your branch, and it looks like the pull request has been closed automatically.

It seems that you have lost your commits with translations somewhere during the rebase, so please recover them and rebase again.

Unfortunately, if you do not have an explicit local backup, you'll have to use a method similar to http://gitready.com/advanced/2009/01/17/restoring-lost-commits.html

**Pull request closed without merging**
