### PR TITLE
Czech translation update

### PR DESCRIPTION
**Pull request by R3gi**
Czech translation update:
• Fix of grammatical, typographical and contextual issues
• Improved translation consistency

### CODE REVIEW

**Comment by mapsmetest** [comment]
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

**Comment by trashkalmar** [comment]
Thank you for corrections!
1. But please modify strings.txt file only, then run tools/unix/generate_localizations.sh to create platform strings.
2. Create two commits: the first with modified strings.txt, the second - with generated strings.xml and localizable.lproj files.

**Comment by R3gi** [comment]
@trashkalmar Thanks, how can I do that? What do you mean by "strings.txt" file? Android is using xml… I am still not so familiar with GitHub web interface and I am not a developer, only translator.

**Comment by trashkalmar** [comment]
There is "strings.txt" file in the project root. This file is the storage of strings used both by Android and iOS applications, thats why we modify it only, not strings.xml.
First, you should commit modifications of strings.txt, then run tools/unix/generate_localizations.sh script and commit its results. It should be done in console on your local computer.

**Comment by R3gi** [comment]
Hmm, I've downloaded GitHub for desktop, cloned the repository (oh, it's so large), edited and saved the strings.txt file on my local HDD, but I can't find a way how to run mentioned script in GitHub app. And I am using Windows, which if I am right doesn't support running *.sh scripts directly via cmd.exe. Is there some other option to submit the translation file?


I am worried that this way of submitting even basic translation updates is too much complicated for translators, it requires a lot of time and I am not sure if every translator want to install X programs just for submitting one localization file. In my opinion this should be changed. Using Crowdin.net or other translation platform would be much more user friendly…

**Comment by Zverik** [comment]
Could you please sign the CLA? http://maps.me/cla/

**Comment by R3gi** [comment]
@Zverik Done! :)

**Comment by trashkalmar** [comment]
@R3gi Thanks! We'll create a pull request with your modifications!

**Comment by trashkalmar** [comment]
@R3gi Could you please send the file to alexm@mapswithme.com? Looks like Bitster.cz is inaccessible outside Czech Republic.

**Comment by R3gi** [comment]
@trashkalmar Thank you for this info. I am very sorry for these complications, GitHub seems to be still very confusing for me…they really should do something with it and make it more friendly for newbies too O:-)

**Pull request closed without merging**
