### PR TITLE
add screenshots to readme

### PR DESCRIPTION
**Pull request by jancborchardt**
This makes the readme and the project on Github a lot more attractive. :)

Simply took the screenshots from the app listing at https://play.google.com/store/apps/details?id=com.mapswithme.maps.pro&hl=en

### CODE REVIEW

**Comment by Zverik** [comment]
Thanks, Jan-Christoph. Alas, these images are in webp format, which some browsers don't show. Like Firefox. Also, we'd prefer to keep everything maps.me-related in this repository.

**Comment by jancborchardt** [comment]
> Alas, these images are in webp format, which some browsers don't show. Like Firefox.

Of course, will change it to .png. Should I combine them to one image also, or leave it 5 separate ones?

> Also, we'd prefer to keep everything maps.me-related in this repository.

So do you mean I should put the screenshots somewhere in this repository and link them in the readme? Then it’s probably best if someone of you adds the originals directly. :)

**Comment by Zverik** [comment]
1) Better combine.
2) Yes, put these into `docs` in this PR.

**Comment by jancborchardt** [comment]
@Zverik cool, thanks! Updated the pull request by force push.

**Comment by jancborchardt** [comment]
Mind reviewing @Zverik @igrechuhin @rokuz? :)

**Pull request merged**
