### PR TITLE
Removed Alohalytics code and use it as a git submodule.

### PR DESCRIPTION
**Pull request by deathbaba**
Don't forget to run ```git submodule update --init --recursive``` after checking out this code.
If you have any git errors about 'Alohalytics already exisists' while updating submodules or switching between branches please delete existing Alohalytics folder first ```rm -rf 3party/Alohalytics``` and repeat.

### CODE REVIEW

**Comment by mapsmetest** [comment]
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

**Comment by deathbaba** [comment]
This request also references newer version of Alohalytics with online/offline statistics for iOS.

**Comment by deathbaba** [comment]
JTTP

**Comment by Zverik** [comment]
LGTM

**Comment by bykoianko** [comment]
LGTM

**Comment by kshalnev** [comment]
LGTM

**Pull request merged**
