### PR TITLE
Fixed building on iOS and Android

### PR DESCRIPTION
**Pull request by rokuz**

### CODE REVIEW

**Comment by Zverik** [comment]
LGTM

**Comment by bykoianko** [comment]
LGTM @igrechuhin @syershov or @VladiMihaylenko PTAL&merge.

**Comment by mapsmetest** [comment]
DUDE JTTP

**Comment by syershov** [comment]
LGTM

**Comment by mapsmetest** [comment]
DUDE JTTP

**Comment by mapsmetest** [comment]
LGTM

**Pull request merged**
