### PR TITLE
[indexer] [search] Enabled the Persian language for categories.

### PR DESCRIPTION
**Pull request by mpimenov**
To make #7526 work.

### CODE REVIEW

**Comment by Zverik** [comment]
DUDE JTTP

**Comment by mapsmetest** [comment]
GitHub Watchdog

**Comment by mapsmetest** [comment]
GitHub Watchdog

**Comment by mapsmetest** [comment]
GitHub Watchdog Failure http://angola.mapsme.mail.msk:8080/job/GitHubWatchdog/

**Pull request merged**
