### PR TITLE
[DO NOT MERGE][styles] Added international names

### PR DESCRIPTION
**Pull request by kshalnev**
https://trello.com/c/BaIJ8H0a/216--

### CODE REVIEW

**Comment by mapsmetest** [comment]
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

**Comment by yunikkk** [comment]
JTTP

**Comment by therearesomewhocallmetim** [comment]
JTTP

**Comment by therearesomewhocallmetim** [comment]
JTTP

**Comment by therearesomewhocallmetim** [comment]
test this please

**Comment by therearesomewhocallmetim** [comment]
JTTP

**Comment by therearesomewhocallmetim** [comment]
JTTP

**Pull request closed without merging**
