### PR TITLE
Fix German translation for dog park

### PR DESCRIPTION
**Pull request by sb12**
Fix German translation for dog park:
"Hundeauflauf" is actually something to eat containing dog meat :(

### CODE REVIEW

**Comment by mpimenov** [comment]
Hello. Please sign the CLA: https://maps.me/cla

**Comment by mpimenov** [comment]
Note that the files you have edited are auto-generated. The source file is here: https://github.com/mapsme/omim/blob/master/data/strings/types_strings.txt#L11049

For more information refer to https://github.com/mapsme/omim/wiki/strings.txt

**Comment by sb12** [comment]
Thanks for the information, somehow I did not find the source file in the github search. 

I changed the source file now as well. Unfortunately, I am not able to change the commit message as suggested in the wiki and I cannot run the files as I only edited the files on the github web interface.

**Comment by mpimenov** [comment]
@sb12 That will do, we'll take care of the rest ourselves. Thanks!

**Pull request merged**
