### PR TITLE
Release 65 to master

### PR DESCRIPTION
**Pull request by igrechuhin**

### CODE REVIEW

**Comment by alexzatsepin** [comment]
LGTM

**Comment by darina** [comment]
LGTM

**Comment by milchakov** [comment]
LGTM

**Comment by mapsmetest** [comment]
DUDE JTTP

**Comment by mapsmetest** [comment]
LGTM

**Comment by Zverik** [comment]
LGTM

**Comment by rokuz** [comment]
LGTM

**Pull request merged**
