### PR TITLE
Update Install.md

### PR DESCRIPTION
**Pull request by halonsoluis**
Fixes relative path to detect_qmake.sh in docs

### CODE REVIEW

**Comment by halonsoluis** [comment]
Appears that in some point the folders hierarchy changed and those changes were not reflected in documentation.

**Comment by deathbaba** [comment]
Thanks! Have you already signed our http://maps.me/cla/ ?

**Comment by halonsoluis** [comment]
Yes, I signed right now. I hope to be contributing further more from now on

**Comment by deathbaba** [comment]
Thanks a lot and Welcome!

**Pull request merged**
