### PR TITLE
[strings] pt_BR translation + adjustments in pt_PT

### PR DESCRIPTION
**Pull request by Zverik**
Rebase of #3846.

Just strings, no support in the code yet.

### CODE REVIEW

**Comment by Zverik** [comment]
@naoliv  @bonix-git Could you please sign [the contributor agreement](http://maps.me/cla/) so we could use your changes?

**Comment by naoliv** [comment]
I signed and asked to @nighto take a look at it too.

**Comment by Zverik** [comment]
Thanks Nelson!

**Comment by nighto** [comment]
Signed too.

**Comment by bonix-git** [comment]
Signed too.

**Comment by willemarcel** [comment]
Some news about this, @Zverik? Next week the https://github.com/mapsme/omim/pull/3846 will complete 10 months without been accepted.

**Pull request closed without merging**
