### PR TITLE
add Persian to strings.txt file

### PR DESCRIPTION
**Pull request by imanmoghimiq30**
add Persian to strings.txt file

### CODE REVIEW

**Comment by mapsmetest** [comment]
Can one of the admins verify this patch?

**Comment by imanmoghimiq30** [comment]
I don.t know
I do not know much about these things
I just translated

**Comment by ayratinirani** [comment]
we are iranian openstreet mapper group and iman is one of this group iranian users all complain that why this app is not in our language many of them migrate to others because of this reason

**Comment by rokuz** [comment]
Hi, could you please rebase your changes?
git rebase master

**Comment by Zverik** [comment]
Rebasing this is not possible for the original uploader, since it must be done on macos/linux. See #8126 for a clean version. Thanks @imanmoghimiq30 for translating the strings.

**Comment by imanmoghimiq30** [comment]
I can't understand what is happening 
what is wrong

**Comment by imanmoghimiq30** [comment]
OK I got it
Seems I deleted some of the parts of code

**Pull request closed without merging**
