### PR TITLE
Improve french translation ; change some verbs declination ; change s…

### PR DESCRIPTION
**Pull request by jfoucry**
Hello there,
New to this project, I will try to improve french translation. I did a first check/change on the faq.html

### CODE REVIEW

**Comment by mpimenov** [comment]
Hello. Please sign the CLA: https://maps.me/cla

**Comment by jfoucry** [comment]
Signed!

**Comment by mpimenov** [comment]
Are you sure? I can't see you in the list of signees.

**Comment by mpimenov** [comment]
@jfoucry ping

**Comment by jfoucry** [comment]
Weel, I resigned the agreement. I did not receive any mail about it.

**Comment by mpimenov** [comment]
This time it worked.
Thanks.

**Comment by mpimenov** [comment]
Apparently the first try did not manage to pass the spam filters but we register it on closer scrutiny. Sorry for the inconvenience.

**Pull request merged**
